htr3n/hyde-hyde

layouts/partials/header/styles-highlight.html
layouts/partials/header/styles.html

This commit shall remove the unnecessary  slash appeared in the generated html files.
We can reproduce the "double slash" with the following config:
`baseurl = "http://localhost/"`
and run following commands
```
hugo
cd public
cat 404.html | grep '\/\/css'
```

Fix css URL

---

exampleSite/config.toml

This is a PR for the config.toml in the example site content.
For some reason, it seems that having `title` in the `[Params]` section doesn't get picked up by Hugo, so I suggest moving it. It seems that your own personal site follows this `config.toml` structure already (https://github.com/htr3n/htr3n-blog/blob/master/config.toml)
I was also curious if the `copyright` value is currently used anywhere in the theme? In your personal site, it's listed in the `config.toml`, but I can't seem to find it displayed anywhere on your live site.

Moved title setting outside of params

---

layouts/partials/sidebar.html

With an authorImage like `/images/me.png`, the authorImage URL was created like `http://example.comimages/me.png`
missing a slash in between the base URL and the image.
This adds the missing slash.

Fix author image URL

---

layouts/partials/sidebar/social.html

Supports [rel-me](http://microformats.org/wiki/rel-me), a commonly used microformat for linking disparate social profiles together. This enables the use of [IndieAuth](https://indieauth.com/) for login on other websites.

Adds XFN rel-me links

---

layouts/partials/portfolio/content.html

Add rel="noopener noreferrer" to all target="_blank" in order to patch a vulnerability presented [here](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/)

Patch vulnerabilities around target="_blank"

---

layouts/partials/header/styles-highlight.html

There is a '+' sign left in one of the header partials, it becomes visible on mobile.

Remove erroneous '+' sign

---

assets/scss/hyde-hyde/_responsive.scss

On mobile the header clickable area is not the full width of header so you can see the padding on the sides when it is tapped. 
This resolves that by removing the padding on the sidebar container and offsetting the background image, the visual results are identical but now the clickable area is the full header.

Fixed mobile header clickable area to be full width

---

README.md
exampleSite/config.toml
layouts/partials/page-single/comment/utterances.html
layouts/partials/page-single/post-comment.html

Added support for another comment system other than disqus or graphcomment.
https://utteranc.es/

Add support for Utterances comments

---

layouts/partials/sidebar.html

Not sure if it fits theme design however I find it extremely useful to have gravatar support so there is no need to store images in the static folder. A previous option is still supported if `authorimage` has been provided. 
Also, not sure if they have to be mutual exclusive.

Add gravatar support

---

layouts/partials/sidebar.html
layouts/partials/sidebar/about.html

The change in PR https://github.com/htr3n/hyde-hyde/pull/37 made it so that there were two slashes instead of one, such that the `authorimage` from the exampleSite would not render.
This PR returns the original code for rendering the `authorimage`, which works with the following `config.toml` settings:
```
[params]
authorimage = "img/hugo.png"
```
or
```
[params]
authorimage = "/img/hugo.png"
```
Both work, such that the `authorimage` appears in the sidebar across the full site, and now the exampleSite `hugo.png` shows up. I am running Hugo 0.52, and using the theme via the R blogdown package. I am unable to replicate the error cited in the original PR.

reverse PR that added additional slash to `authorimage` file path

---

layouts/partials/sidebar/social.html

This patch allows to specify another gitlab domain name to be used in the links of the social bar.
It can be configured in `[params.social]` section of the config file like:
```toml
[params.social]
gitlab = "Kerl13"
custom_gitlab_domain = "gitlab.somewhere.com"
```
By default `gitlab.com` is used (the current behaviour)

Custom gitlab domains

---

layouts/partials/header/feeds.html

This fixes the deprecation notice: `Page's .RSSLink is deprecated and will be removed in a future release.`
I adjusted the template to the referenced in the hugo docs: https://gohugo.io/templates/rss/#reference-your-rss-feed-in-head

Stop using deprecated .RSSLink

---

README.md
layouts/partials/page-single/content.html
layouts/partials/page-single/footer.html

`include_toc = false`: Setting to `false` in FrontMatter will disable too short TOC data as your want. 
```
---
title: "I dot not want TOC in this page"
include_toc: false
---
```

add include_toc options 

---

layouts/partials/header/meta.html

Fixes deprecation message:
> Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.

Convert deprecated .Hugo to hugo function

---

layouts/partials/portfolio/content.html

I had to unquote the true value in the where expression on Params.featured to make it work.
My Hugo version is:
Hugo Static Site Generator v0.54.0/extended darwin/amd64 BuildDate: unknown

Unquoting true value for Params.featured

---

layouts/index.html

Adjusting the index page to show all the posts in descending order in the version [v0.57.0](https://github.com/gohugoio/hugo/releases/tag/v0.57.0) of Hugo.
After the changes in gohugoio/hugo#6181 included in the version v0.57.0 of Hugo the index page shows the post category instead of all the posts.
*This use of `.Site.RegularPages` keeps retro-compatibility with previous versions of Hugo.*

Adjusted post list for Hugo v0.57.0

---

layouts/index.html

Reverts htr3n/hyde-hyde#82
The changes actually work. The other revert is due to some incorrect local settings.

Revert "Revert "Adjusted post list for Hugo v0.57.0""

---

exampleSite/config.toml
layouts/partials/sidebar/copyright.html

.Site.Params.since is an option to store the year site development started. Makes possible things like:
(c) 2019 - 2020

add .Site.Params.since

---

layouts/partials/header/meta.html

Per standard, "Cache-Control" is not a valid http-equiv keyword.
https://html.spec.whatwg.org/multipage/semantics.html#pragma-directives
W3C validator marks the corresponding lines as invalid HTML.

remove Cache-Control meta header

---

layouts/partials/portfolio/content.html

In this way, screenshot becomes optional for a project. I.e. you can omit "screenshot: dera.png" in the front matter.
This is how it looks like when a screenshot is not defined in the front matter for a project before and after this commit.
It's the first time I play with hugo, so feel free to adjust the code.

Portfolio: load project screenshot only if defined

---

layouts/partials/header.html

By default the page permalink is used, if necessary a custom `canonicalUrl` parameter can be set in a page front matter.
The canonical URL link is often used to handle "duplicated" pages in the same website or even when the same content is posted in multiple website.

Add canonical URL link in header.html

---

layouts/partials/sidebar/social.html

Chose to use the "fas fa-cube" icon since I saw it used elsewhere for the same purpose. 
This uses a similar Param as all other socials:
[params.social]
hackthebox = # profile_id from: https://www.hackthebox.eu/home/users/profile/{profile_id}
Apologies for any breaks in typical process, this is my first pull request :)

Added hackthebox.eu to social sidebar HTML
